import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
};

export default function TermsPage() {
  return (
    <main
      id="main-content"
      className="min-h-screen px-6 py-16"
      style={{ background: "var(--surface-base)", color: "var(--text-primary)" }}
    >
      <div className="max-w-[640px] mx-auto">
        <Link
          href="/"
          className="text-xs text-(--text-tertiary) no-underline hover:text-(--text-secondary) transition-colors mb-8 inline-block"
        >
          &larr; Back to Sift
        </Link>
        <h1 className="font-heading text-3xl font-bold mb-6">Terms of Service</h1>

        <div className="space-y-6 text-sm leading-relaxed text-(--text-secondary)">
          <section>
            <h2 className="font-heading text-lg font-bold text-(--text-primary) mb-2">What Sift does</h2>
            <p>
              Sift aggregates and summarizes publicly available news using AI. Every article links
              to the original source. Summaries are generated by AI and may not perfectly represent
              the original content.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-bold text-(--text-primary) mb-2">Use of the service</h2>
            <p>
              Sift is provided as-is for informational purposes. You may use it for personal,
              non-commercial purposes. Don&apos;t scrape, redistribute, or misrepresent Sift content
              as your own.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-bold text-(--text-primary) mb-2">AI-generated content</h2>
            <p>
              Summaries, comparisons, and topic interpretations are generated by AI. They may
              contain errors. Always verify important information against the original sources,
              which are linked from every article.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-lg font-bold text-(--text-primary) mb-2">Availability</h2>
            <p>
              We aim for high uptime but don&apos;t guarantee uninterrupted service. Features may
              change as the product evolves.
            </p>
          </section>
        </div>

        <p className="text-xs text-(--text-tertiary) mt-10">
          Last updated: April 2026
        </p>
      </div>
    </main>
  );
}
